#include "config.hpp"
#include <iostream>
#include <regex>
#include <filesystem>

namespace HandWrite {

Config::Config(const std::string& path) {
    load(path);
}

bool Config::load(const std::string& path) {
    std::ifstream file(path);
    if (!file.is_open()) {
        std::cerr << "Warning: Configuration file not found at " << path << std::endl;
        return false;
    }
    
    std::string line;
    while (std::getline(file, line)) {
        line = trim(line);
        
        // Skip empty lines and comments
        if (line.empty() || line[0] == '#') {
            continue;
        }
        
        // Find key-value separator
        size_t eqPos = line.find('=');
        if (eqPos == std::string::npos) {
            continue;
        }
        
        std::string key = trim(line.substr(0, eqPos));
        std::string value = trim(line.substr(eqPos + 1));
        
        // Remove quotes from string values
        if (value.size() >= 2 && value.front() == '"' && value.back() == '"') {
            value = value.substr(1, value.size() - 2);
            m_data[key] = value;
        }
        // 数组值
        else if (value.front() == '[') {
            // 移除方括号
            std::string arrayContent = value.substr(1, value.size() - 2);
            std::stringstream ss(arrayContent);
            std::string item;
            std::vector<int> intArray;
            std::vector<double> doubleArray;
            bool isDouble = false;
            
            while (std::getline(ss, item, ',')) {
                item = trim(item);
                if (item.find('.') != std::string::npos) {
                    isDouble = true;
                    doubleArray.push_back(std::stod(item));
                } else {
                    intArray.push_back(std::stoi(item));
                }
            }
            
            if (isDouble) {
                m_data[key] = doubleArray;
            } else {
                m_data[key] = intArray;
            }
        }
        // Numeric values
        else if (value.find('.') != std::string::npos) {
            m_data[key] = std::stod(value);
        }
        else {
            try {
                m_data[key] = std::stoi(value);
            } catch (...) {
                m_data[key] = value;
            }
        }
    }
    
    return true;
}

bool Config::save(const std::string& path) {
    std::ofstream file(path);
    if (!file.is_open()) {
        std::cerr << "Error: Cannot open file for writing: " << path << std::endl;
        return false;
    }
    
    file << "# HandWrite Configuration File\n";
    file << "# Generated by HandWrite-CPP\n\n";
    
    for (const auto& [key, value] : m_data) {
        file << key << " = " << valueToString(value) << "\n";
    }
    
    file.close();
    std::cout << "Configuration saved to " << path << std::endl;
    return true;
}

std::string Config::trim(const std::string& str) const {
    size_t start = str.find_first_not_of(" \t\r\n");
    if (start == std::string::npos) {
        return "";
    }
    size_t end = str.find_last_not_of(" \t\r\n");
    return str.substr(start, end - start + 1);
}

std::string Config::valueToString(const Value& value) const {
    if (std::holds_alternative<int>(value)) {
        return std::to_string(std::get<int>(value));
    }
    else if (std::holds_alternative<double>(value)) {
        std::ostringstream oss;
        oss << std::get<double>(value);
        return oss.str();
    }
    else if (std::holds_alternative<std::string>(value)) {
        return "\"" + std::get<std::string>(value) + "\"";
    }
    else if (std::holds_alternative<std::vector<int>>(value)) {
        const auto& arr = std::get<std::vector<int>>(value);
        std::string result = "[";
        for (size_t i = 0; i < arr.size(); ++i) {
            result += std::to_string(arr[i]);
            if (i < arr.size() - 1) {
                result += ", ";
            }
        }
        result += "]";
        return result;
    }
    else if (std::holds_alternative<std::vector<double>>(value)) {
        const auto& arr = std::get<std::vector<double>>(value);
        std::string result = "[";
        for (size_t i = 0; i < arr.size(); ++i) {
            std::ostringstream oss;
            oss << arr[i];
            result += oss.str();
            if (i < arr.size() - 1) {
                result += ", ";
            }
        }
        result += "]";
        return result;
    }
    return "";
}

std::optional<int> Config::getInt(const std::string& key) const {
    auto it = m_data.find(key);
    if (it != m_data.end() && std::holds_alternative<int>(it->second)) {
        return std::get<int>(it->second);
    }
    return std::nullopt;
}

std::optional<double> Config::getDouble(const std::string& key) const {
    auto it = m_data.find(key);
    if (it != m_data.end()) {
        if (std::holds_alternative<double>(it->second)) {
            return std::get<double>(it->second);
        } else if (std::holds_alternative<int>(it->second)) {
            return static_cast<double>(std::get<int>(it->second));
        }
    }
    return std::nullopt;
}

std::optional<std::string> Config::getString(const std::string& key) const {
    auto it = m_data.find(key);
    if (it != m_data.end() && std::holds_alternative<std::string>(it->second)) {
        return std::get<std::string>(it->second);
    }
    return std::nullopt;
}

std::optional<std::vector<int>> Config::getIntArray(const std::string& key) const {
    auto it = m_data.find(key);
    if (it != m_data.end() && std::holds_alternative<std::vector<int>>(it->second)) {
        return std::get<std::vector<int>>(it->second);
    }
    return std::nullopt;
}

std::optional<std::vector<double>> Config::getDoubleArray(const std::string& key) const {
    auto it = m_data.find(key);
    if (it != m_data.end() && std::holds_alternative<std::vector<double>>(it->second)) {
        return std::get<std::vector<double>>(it->second);
    }
    return std::nullopt;
}

void Config::set(const std::string& key, int value) {
    m_data[key] = value;
}

void Config::set(const std::string& key, double value) {
    m_data[key] = value;
}

void Config::set(const std::string& key, const std::string& value) {
    m_data[key] = value;
}

void Config::set(const std::string& key, const std::vector<int>& value) {
    m_data[key] = value;
}

void Config::set(const std::string& key, const std::vector<double>& value) {
    m_data[key] = value;
}

bool Config::has(const std::string& key) const {
    return m_data.find(key) != m_data.end();
}

// Property-style accessors
std::optional<int> Config::width() const { return getInt("width"); }
void Config::setWidth(int value) { set("width", value); }

std::optional<int> Config::height() const { return getInt("height"); }
void Config::setHeight(int value) { set("height", value); }

std::optional<std::string> Config::ttfSelector() const { return getString("ttf_selector"); }
void Config::setTtfSelector(const std::string& value) { set("ttf_selector", value); }

std::optional<int> Config::fontSize() const { return getInt("font_size"); }
void Config::setFontSize(int value) { set("font_size", value); }

std::optional<int> Config::lineSpacing() const { return getInt("line_spacing"); }
void Config::setLineSpacing(int value) { set("line_spacing", value); }

std::optional<int> Config::charDistance() const { return getInt("char_distance"); }
void Config::setCharDistance(int value) { set("char_distance", value); }

std::optional<int> Config::marginTop() const { return getInt("margin_top"); }
void Config::setMarginTop(int value) { set("margin_top", value); }

std::optional<int> Config::marginBottom() const { return getInt("margin_bottom"); }
void Config::setMarginBottom(int value) { set("margin_bottom", value); }

std::optional<int> Config::marginLeft() const { return getInt("margin_left"); }
void Config::setMarginLeft(int value) { set("margin_left", value); }

std::optional<int> Config::marginRight() const { return getInt("margin_right"); }
void Config::setMarginRight(int value) { set("margin_right", value); }

std::optional<std::vector<int>> Config::charColor() const { return getIntArray("char_color"); }
void Config::setCharColor(const std::vector<int>& value) { set("char_color", value); }

std::optional<std::vector<int>> Config::backgroundColor() const { return getIntArray("background_color"); }
void Config::setBackgroundColor(const std::vector<int>& value) { set("background_color", value); }

std::optional<int> Config::resolution() const { return getInt("resolution"); }
void Config::setResolution(int value) { set("resolution", value); }

std::optional<double> Config::lineSpacingSigma() const { return getDouble("line_spacing_sigma"); }
void Config::setLineSpacingSigma(double value) { set("line_spacing_sigma", value); }

std::optional<double> Config::fontSizeSigma() const { return getDouble("font_size_sigma"); }
void Config::setFontSizeSigma(double value) { set("font_size_sigma", value); }

std::optional<double> Config::wordSpacingSigma() const { return getDouble("word_spacing_sigma"); }
void Config::setWordSpacingSigma(double value) { set("word_spacing_sigma", value); }

std::optional<double> Config::perturbXSigma() const { return getDouble("perturb_x_sigma"); }
void Config::setPerturbXSigma(double value) { set("perturb_x_sigma", value); }

std::optional<double> Config::perturbYSigma() const { return getDouble("perturb_y_sigma"); }
void Config::setPerturbYSigma(double value) { set("perturb_y_sigma", value); }

std::optional<double> Config::perturbThetaSigma() const { return getDouble("perturb_theta_sigma"); }
void Config::setPerturbThetaSigma(double value) { set("perturb_theta_sigma", value); }

} // namespace HandWrite
